### ISSUE TITLE
gfortran-11.4 Internal Compiler Error building test_network.f90

### ISSUE THREAD

**Issue by milancurcic** [nedtaylor/athena#20]
```
...
test_dropblock3d_layer.f90             done.
test_network.f90                       failed.
[ 63%] Compiling...
f951: internal compiler error: Segmentation fault
0x74e33f24251f ???
        ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
0x74e33f229d8f __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x74e33f229e3f __libc_start_main_impl
        ../csu/libc-start.c:392
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
<ERROR> Compilation failed for object " test_test_network.f90.o "
<ERROR> stopping due to failed compilation
STOP 1
```

I can see that the README states that the lowest tested gfortran is v13, and that the library is possibly not expected to build with lower version. Reporting here nevertheless to document the issue.

**Comment by milancurcic** [comment]
The issue occurs with `--profile debug` as well.

**Comment by milancurcic** [comment]
Correction, v12.3 doesn't encounter this issue.

**Comment by milancurcic** [comment]
@nedtaylor Can you put an update to the README.md that the library works with v12.3?

**Comment by nedtaylor** [comment]
> @nedtaylor Can you put an update to the README.md that the library works with v12.3?

@milancurcic Reference added in commit 5882155ff5e11d12cf041e5d097823e37de6323f.

**Comment by nedtaylor** [comment]
Leaving this issue open for now as I will look into why it fails for v11.4 and whether this can be fixed at some point.

**Comment by nedtaylor** [comment]
The library no longer compiles with gcc < 14.3 due to known gcc bugs. Therefore, support of 11.4 is no longer possible.
